name = input("What is your name? ")
print("Hello", name)
country = input("Which country are you from? ")
print("You are from", country)
age = input("Enter your age: ")
age = int(age)
print(age + 5)
height = float(input("Enter your height: "))
print(height)