# tools/verified_agents_and_homes.py


COMPANY_NAME = "Verified Agents and Homes"
COMPANY_TAGLINE = "Verify Before You Buy, Rent, Book, or Pay"


COMPANY_DESCRIPTION = """
Verified Agents and Homes is a property and real-estate verification
service designed to help people make safer property and accommodation
decisions.

The service helps customers verify property documents, land documents,
building approvals, real-estate agents, short-let addresses, short-let
owners, and short-let managers before making transactions.

The platform also keeps verification information that may be updated
regularly. Customers should always check the latest information on the
Verified Agents and Homes database/platform before making any payment
or transaction.
"""


WHAT_WE_DO = [
    "Land and house document search and verification",
    "Property ownership document verification",
    "Building approval verification",
    "Property verification",
    "Real-estate agent verification",
    "Agent document verification",
    "Short-let address verification",
    "Short-let owner verification",
    "Short-let manager verification",
    "Monthly verification updates",
    "Reporting and review of verification concerns",
]


LAGOS_LOCATIONS = [
    "Lagos Island",
    "Victoria Island",
    "Ikoyi",
    "Lekki",
    "Ajah",
    "Sangotedo",
    "Chevron",
    "Ikate",
    "Osapa",
    "Yaba",
    "Surulere",
    "Ikeja",
    "Maryland",
    "Magodo",
    "Gbagada",
    "Festac",
    "Badagry",
    "Epe",
    "Ibeju-Lekki",
]


# -------------------------------------------------------------------
# SAMPLE PROPERTY DATABASE
# -------------------------------------------------------------------
# These are sample records for development and testing.
# They can later be replaced with the real database.
# -------------------------------------------------------------------

PROPERTIES = {
    "VAH-001": {
        "location": "Lekki, Lagos",
        "lga": "Ibeju-Lekki",
        "property_type": "Detached House",
        "category": "House",
        "property_status": "Verification Pending",
        "owner_documents": {
            "Deed of Assignment": "Submitted",
        },
        "land_documents": {
            "Survey Plan": "Submitted",
        },
        "house_documents": {
            "Approved Building Plan": "Submitted",
        },
        "building_approval": "Not Verified",
    },
    "VAH-002": {
        "location": "Ikoyi, Lagos",
        "lga": "Eti-Osa",
        "property_type": "Apartment",
        "category": "House",
        "property_status": "Verified",
        "owner_documents": {
            "Deed of Assignment": "Verified",
            "Certificate of Occupancy (C of O)": "Verified",
        },
        "land_documents": {
            "Survey Plan": "Verified",
            "Certificate of Occupancy (C of O)": "Verified",
        },
        "house_documents": {
            "Approved Building Plan": "Verified",
        },
        "building_approval": "Verified",
    },
    "VAH-003": {
        "location": "Victoria Island, Lagos",
        "lga": "Eti-Osa",
        "property_type": "Terrace House",
        "category": "House",
        "property_status": "Verification Pending",
        "owner_documents": {
            "Deed of Assignment": "Submitted",
        },
        "land_documents": {
            "Survey Plan": "Submitted",
        },
        "house_documents": {
            "Approved Building Plan": "Pending",
        },
        "building_approval": "Pending",
    },
    "VAH-004": {
        "location": "Badagry, Lagos",
        "lga": "Badagry",
        "property_type": "Detached House",
        "category": "House",
        "property_status": "Verification Pending",
        "owner_documents": {
            "Deed of Assignment": "Submitted",
        },
        "land_documents": {
            "Survey Plan": "Submitted",
            "Certificate of Occupancy (C of O)": "Submitted",
        },
        "house_documents": {
            "Approved Building Plan": "Submitted",
        },
        "building_approval": "Pending",
    },
}


# -------------------------------------------------------------------
# SAMPLE AGENT DATABASE
# -------------------------------------------------------------------
# IMPORTANT:
# Agent ID and VAH Verification Number are NOT the same thing.
#
# Agent ID:
#   A permanent/internal identification reference for the agent.
#
# VAH Verification Number:
#   A customer-facing verification number that changes every month.
#
# The numbers below are SAMPLE numbers for development.
# They should be replaced by the actual numbers generated by the
# Verified Agents and Homes database/platform.
# -------------------------------------------------------------------

AGENTS = {
    "AG-001": {
        "name": "John Adewale",
        "phone": "08012345678",
        "agency": "Adewale Properties",
        "picture": "Recorded",
        "verification_status": "Verified",
        "identity_document": "Verified",
        "license_status": "Verified",
        "current_address": "Not yet recorded",
        "address_update_status": "Update Required",

        "verification_number": "VAH-SAMPLE-001-2026-09",
        "verification_number_status": "Current",
        "verification_number_month": "2026-09",
        "verification_number_update_frequency": "Monthly",

        "monthly_update": {
            "frequency": "Monthly",
            "last_update": "Not yet recorded",
            "next_update": "Monthly review required",
        },

        "reports": [],

        "documents": {
            "Government ID": "Verified",
            "Real Estate License": "Verified",
            "Agency Registration": "Verified",
        },
    },

    "AG-002": {
        "name": "Sarah Okafor",
        "phone": "08023456789",
        "agency": "Sarah Homes",
        "picture": "Recorded",
        "verification_status": "Verification Pending",
        "identity_document": "Submitted",
        "license_status": "Pending",
        "current_address": "Not yet recorded",
        "address_update_status": "Update Required",

        "verification_number": "VAH-SAMPLE-002-2026-09",
        "verification_number_status": "Current",
        "verification_number_month": "2026-09",
        "verification_number_update_frequency": "Monthly",

        "monthly_update": {
            "frequency": "Monthly",
            "last_update": "Not yet recorded",
            "next_update": "Monthly review required",
        },

        "reports": [],

        "documents": {
            "Government ID": "Submitted",
            "Real Estate License": "Pending",
            "Agency Registration": "Submitted",
        },
    },

    "AG-003": {
        "name": "David Williams",
        "phone": "08034567890",
        "agency": "Williams Realty",
        "picture": "Recorded",
        "verification_status": "Verified",
        "identity_document": "Verified",
        "license_status": "Verified",
        "current_address": "Not yet recorded",
        "address_update_status": "Update Required",

        "verification_number": "VAH-SAMPLE-003-2026-09",
        "verification_number_status": "Current",
        "verification_number_month": "2026-09",
        "verification_number_update_frequency": "Monthly",

        "monthly_update": {
            "frequency": "Monthly",
            "last_update": "Not yet recorded",
            "next_update": "Monthly review required",
        },

        "reports": [],

        "documents": {
            "Government ID": "Verified",
            "Real Estate License": "Verified",
            "Agency Registration": "Verified",
        },
    },
}


# -------------------------------------------------------------------
# SAMPLE SHORT-LET DATABASE
# -------------------------------------------------------------------

SHORTLETS = {
    "VAH-001": {
        "property_id": "VAH-001",
        "current_look": "Not yet recorded",
        "current_look_status": "Update Required",
        "last_update": "Not yet recorded",
        "reported_issues": [],
        "verification_status": "Verification Pending",
    },

    "VAH-002": {
        "property_id": "VAH-002",
        "current_look": "Not yet recorded",
        "current_look_status": "Update Required",
        "last_update": "Not yet recorded",
        "reported_issues": [],
        "verification_status": "Verified",
    },

    "VAH-003": {
        "property_id": "VAH-003",
        "current_look": "Not yet recorded",
        "current_look_status": "Update Required",
        "last_update": "Not yet recorded",
        "reported_issues": [],
        "verification_status": "Verification Pending",
    },

    "VAH-004": {
        "property_id": "VAH-004",
        "current_look": "Not yet recorded",
        "current_look_status": "Update Required",
        "last_update": "Not yet recorded",
        "reported_issues": [],
        "verification_status": "Verification Pending",
    },
}


VERIFICATION_STATUSES = [
    "Submitted",
    "Pending",
    "Verified",
    "Not Verified",
    "Reported",
    "Under Review",
    "Confirmed",
]


# -------------------------------------------------------------------
# HELPER FUNCTIONS
# -------------------------------------------------------------------

def find_lagos_location(location):
    """Check whether a location is listed in the Lagos service area."""

    if not location:
        return "Please provide a location."

    location_lower = location.lower()

    matches = [
        area
        for area in LAGOS_LOCATIONS
        if area.lower() in location_lower
    ]

    if matches:
        return (
            f"Location found in Lagos service area: "
            f"{', '.join(matches)}"
        )

    return (
        f"No exact match was found for '{location}'. "
        "Please provide a more specific Lagos location."
    )


def _property_exists(property_id):
    """Check whether a property exists."""

    return property_id in PROPERTIES


def _format_documents(documents):
    """Format a document dictionary for display."""

    if not documents:
        return "No documents recorded."

    return "\n".join(
        f"- {name}: {status}"
        for name, status in documents.items()
    )


def _format_document_status(documents):
    """Return a simple document status summary."""

    if not documents:
        return "No documents recorded."

    statuses = list(documents.values())

    if all(status == "Verified" for status in statuses):
        return "All recorded documents are Verified."

    return "Some documents are still pending verification."


# -------------------------------------------------------------------
# COMPANY INFORMATION
# -------------------------------------------------------------------

def get_company_information():
    """Return general information about Verified Agents and Homes."""

    return (
        f"{COMPANY_NAME}\n"
        f"{COMPANY_TAGLINE}\n\n"
        f"{COMPANY_DESCRIPTION}\n\n"
        "Core Services:\n"
        + "\n".join(f"- {service}" for service in WHAT_WE_DO)
        + "\n\n"
        "Important Safety Rule:\n"
        "Always check the current information on the Verified Agents "
        "and Homes database/platform immediately before making a "
        "transaction."
    )


def get_company_services():
    """Return the company's services."""

    return (
        f"{COMPANY_NAME} Services:\n\n"
        + "\n".join(f"- {service}" for service in WHAT_WE_DO)
    )


def get_company_mission():
    """Return the company mission."""

    return (
        "Our mission is to help people make safer and more informed "
        "property and accommodation decisions by providing reliable "
        "verification services."
    )


def get_company_vision():
    """Return the company vision."""

    return (
        "Our vision is to build a trusted verification platform where "
        "people can check property, agent, owner, manager, address, "
        "and document information before making real-estate transactions."
    )


def get_company_values():
    """Return the company's core values."""

    return (
        "Core Values:\n"
        "- Verification\n"
        "- Transparency\n"
        "- Trust\n"
        "- Accountability\n"
        "- Safety\n"
        "- Accuracy\n"
        "- Customer Protection"
    )


def get_company_story():
    """Return a short company story."""

    return (
        "Verified Agents and Homes was created to help reduce the risks "
        "people face when buying, renting, booking, or dealing with "
        "property agents. The service focuses on verification before "
        "customers commit their money."
    )


def get_company_commitment():
    """Return the company's customer commitment."""

    return (
        "Verified Agents and Homes is committed to encouraging customers "
        "to verify information before making financial commitments. "
        "Customers should always check the latest database update and "
        "current VAH Verification Number before transacting with an agent."
    )


# -------------------------------------------------------------------
# PROPERTY FUNCTIONS
# -------------------------------------------------------------------

def search_property(property_id):
    """Search for a property using its property ID."""

    property_data = PROPERTIES.get(property_id)

    if property_data is None:
        return f"No property was found with ID '{property_id}'."

    return (
        f"Property ID: {property_id}\n"
        f"Location: {property_data['location']}\n"
        f"LGA: {property_data['lga']}\n"
        f"Property Type: {property_data['property_type']}\n"
        f"Category: {property_data['category']}\n"
        f"Property Status: {property_data['property_status']}\n"
        f"Building Approval: {property_data['building_approval']}"
    )


def verify_property(property_id):
    """Return the current verification status of a property."""

    property_data = PROPERTIES.get(property_id)

    if property_data is None:
        return f"No property was found with ID '{property_id}'."

    return (
        f"Property Verification\n"
        f"Property ID: {property_id}\n"
        f"Location: {property_data['location']}\n"
        f"Property Type: {property_data['property_type']}\n"
        f"Verification Status: "
        f"{property_data['property_status']}\n"
        f"Building Approval: {property_data['building_approval']}\n\n"
        "Always confirm the latest verification status on the "
        "Verified Agents and Homes database before making payment."
    )


def search_property_documents(property_id):
    """Search all recorded documents for a property."""

    property_data = PROPERTIES.get(property_id)

    if property_data is None:
        return f"No property was found with ID '{property_id}'."

    return (
        f"Property Documents\n"
        f"Property ID: {property_id}\n\n"
        "Owner Documents:\n"
        f"{_format_documents(property_data['owner_documents'])}\n\n"
        "Land Documents:\n"
        f"{_format_documents(property_data['land_documents'])}\n\n"
        "House Documents:\n"
        f"{_format_documents(property_data['house_documents'])}"
    )


def verify_property_documents(property_id):
    """Return a summary of property document verification."""

    property_data = PROPERTIES.get(property_id)

    if property_data is None:
        return f"No property was found with ID '{property_id}'."

    all_documents = {}

    all_documents.update(property_data["owner_documents"])
    all_documents.update(property_data["land_documents"])
    all_documents.update(property_data["house_documents"])

    return (
        f"Property Document Verification\n"
        f"Property ID: {property_id}\n"
        f"Overall Status: "
        f"{_format_document_status(all_documents)}\n\n"
        "Owner Documents:\n"
        f"{_format_documents(property_data['owner_documents'])}\n\n"
        "Land Documents:\n"
        f"{_format_documents(property_data['land_documents'])}\n\n"
        "House Documents:\n"
        f"{_format_documents(property_data['house_documents'])}"
    )


def search_land_documents(property_id):
    """Search land documents for a property."""

    property_data = PROPERTIES.get(property_id)

    if property_data is None:
        return f"No property was found with ID '{property_id}'."

    return (
        f"Land Documents for {property_id}\n\n"
        f"{_format_documents(property_data['land_documents'])}"
    )


def verify_land_documents(property_id):
    """Verify the recorded land documents for a property."""

    property_data = PROPERTIES.get(property_id)

    if property_data is None:
        return f"No property was found with ID '{property_id}'."

    status = _format_document_status(
        property_data["land_documents"]
    )

    return (
        f"Land Document Verification\n"
        f"Property ID: {property_id}\n"
        f"Status: {status}\n\n"
        f"{_format_documents(property_data['land_documents'])}"
    )


def search_house_documents(property_id):
    """Search house documents for a property."""

    property_data = PROPERTIES.get(property_id)

    if property_data is None:
        return f"No property was found with ID '{property_id}'."

    return (
        f"House Documents for {property_id}\n\n"
        f"{_format_documents(property_data['house_documents'])}"
    )


def verify_house_documents(property_id):
    """Verify house documents for a property."""

    property_data = PROPERTIES.get(property_id)

    if property_data is None:
        return f"No property was found with ID '{property_id}'."

    status = _format_document_status(
        property_data["house_documents"]
    )

    return (
        f"House Document Verification\n"
        f"Property ID: {property_id}\n"
        f"Status: {status}\n\n"
        f"{_format_documents(property_data['house_documents'])}"
    )


def search_location(location):
    """Search whether a location is within the Lagos service area."""

    return find_lagos_location(location)


# -------------------------------------------------------------------
# SHORT-LET FUNCTIONS
# -------------------------------------------------------------------

def verify_shortlet_address(property_id):
    """Verify a short-let address using the property database."""

    property_data = PROPERTIES.get(property_id)

    if property_data is None:
        return f"No property was found with ID '{property_id}'."

    shortlet_data = SHORTLETS.get(property_id)

    if shortlet_data is None:
        return (
            f"No short-let record was found for property "
            f"'{property_id}'."
        )

    return (
        f"Short-let Address Verification\n"
        f"Property ID: {property_id}\n"
        f"Address/Location: {property_data['location']}\n"
        f"LGA: {property_data['lga']}\n"
        f"Current Status: {shortlet_data['verification_status']}\n"
        f"Current Look Status: "
        f"{shortlet_data['current_look_status']}\n\n"
        "Confirm the latest address information before booking "
        "or making payment."
    )


def verify_shortlet_owner(property_id):
    """Return short-let owner verification information."""

    property_data = PROPERTIES.get(property_id)

    if property_data is None:
        return f"No property was found with ID '{property_id}'."

    return (
        f"Short-let Owner Verification\n"
        f"Property ID: {property_id}\n"
        f"Location: {property_data['location']}\n"
        f"Property Status: {property_data['property_status']}\n\n"
        "Owner verification must be confirmed using the latest "
        "Verified Agents and Homes database information before payment."
    )


def verify_shortlet_manager(property_id):
    """Return short-let manager verification information."""

    property_data = PROPERTIES.get(property_id)

    if property_data is None:
        return f"No property was found with ID '{property_id}'."

    return (
        f"Short-let Manager Verification\n"
        f"Property ID: {property_id}\n"
        f"Location: {property_data['location']}\n"
        f"Property Status: {property_data['property_status']}\n\n"
        "Manager information should be confirmed through the latest "
        "Verified Agents and Homes database before booking or payment."
    )


# -------------------------------------------------------------------
# AGENT FUNCTIONS
# -------------------------------------------------------------------

def search_agent(agent_id):
    """Search for an agent using Agent ID."""

    agent_data = AGENTS.get(agent_id)

    if agent_data is None:
        return f"No agent was found with ID '{agent_id}'."

    return (
        f"Agent ID: {agent_id}\n"
        f"Name: {agent_data['name']}\n"
        f"Phone: {agent_data['phone']}\n"
        f"Agency: {agent_data['agency']}\n"
        f"Picture: {agent_data['picture']}\n"
        f"Verification Status: {agent_data['verification_status']}\n"
        f"VAH Verification Number: "
        f"{agent_data['verification_number']}\n"
        f"Verification Number Status: "
        f"{agent_data['verification_number_status']}\n"
        f"Verification Number Month: "
        f"{agent_data['verification_number_month']}"
    )


def search_agent_by_name(name):
    """Search for an agent by name."""

    if not name:
        return "Please provide the agent's name."

    name_lower = name.lower()

    matches = []

    for agent_id, agent_data in AGENTS.items():
        if name_lower in agent_data["name"].lower():
            matches.append(
                f"Agent ID: {agent_id}\n"
                f"Name: {agent_data['name']}\n"
                f"Agency: {agent_data['agency']}\n"
                f"Phone: {agent_data['phone']}\n"
                f"Verification Status: "
                f"{agent_data['verification_status']}\n"
                f"VAH Verification Number: "
                f"{agent_data['verification_number']}\n"
            )

    if not matches:
        return f"No agent was found matching '{name}'."

    return "\n".join(matches)


def verify_agent(agent_id):
    """Verify an agent and show current verification information."""

    agent_data = AGENTS.get(agent_id)

    if agent_data is None:
        return f"No agent was found with ID '{agent_id}'."

    return (
        f"Agent Verification\n"
        f"Agent ID: {agent_id}\n"
        f"Name: {agent_data['name']}\n"
        f"Agency: {agent_data['agency']}\n"
        f"Verification Status: "
        f"{agent_data['verification_status']}\n"
        f"VAH Verification Number: "
        f"{agent_data['verification_number']}\n"
        f"Verification Number Status: "
        f"{agent_data['verification_number_status']}\n"
        f"Verification Number Month: "
        f"{agent_data['verification_number_month']}\n"
        f"Identity Document: "
        f"{agent_data['identity_document']}\n"
        f"Real Estate License: "
        f"{agent_data['license_status']}\n"
        f"Current Address: "
        f"{agent_data['current_address']}\n\n"
        "IMPORTANT:\n"
        "The VAH Verification Number changes every month. "
        "Customers must check the current VAH Verification Number "
        "and latest verification status on the Verified Agents and "
        "Homes database/platform immediately before making any "
        "transaction or payment. Do not rely on an old number."
    )


def search_agent_documents(agent_id):
    """Search documents belonging to an agent."""

    agent_data = AGENTS.get(agent_id)

    if agent_data is None:
        return f"No agent was found with ID '{agent_id}'."

    return (
        f"Agent Documents\n"
        f"Agent ID: {agent_id}\n"
        f"Name: {agent_data['name']}\n\n"
        f"{_format_documents(agent_data['documents'])}"
    )


def verify_agent_documents(agent_id):
    """Verify the recorded documents for an agent."""

    agent_data = AGENTS.get(agent_id)

    if agent_data is None:
        return f"No agent was found with ID '{agent_id}'."

    status = _format_document_status(
        agent_data["documents"]
    )

    return (
        f"Agent Document Verification\n"
        f"Agent ID: {agent_id}\n"
        f"Name: {agent_data['name']}\n"
        f"Overall Status: {status}\n\n"
        f"{_format_documents(agent_data['documents'])}"
    )


# -------------------------------------------------------------------
# MONTHLY AGENT UPDATE FUNCTIONS
# -------------------------------------------------------------------

def get_agent_monthly_update(agent_id):
    """Return the agent's monthly update information."""

    agent_data = AGENTS.get(agent_id)

    if agent_data is None:
        return f"No agent was found with ID '{agent_id}'."

    monthly = agent_data["monthly_update"]

    return (
        f"Monthly Agent Update\n"
        f"Agent ID: {agent_id}\n"
        f"Agent Name: {agent_data['name']}\n"
        f"Update Frequency: {monthly['frequency']}\n"
        f"Last Update: {monthly['last_update']}\n"
        f"Next Update: {monthly['next_update']}\n"
        f"Current Address: {agent_data['current_address']}\n"
        f"Address Update Status: "
        f"{agent_data['address_update_status']}\n\n"
        "The agent's VAH Verification Number is also updated "
        "monthly. Always check the latest database record before "
        "making a transaction."
    )


def get_agent_reports(agent_id):
    """Return reports recorded against an agent."""

    agent_data = AGENTS.get(agent_id)

    if agent_data is None:
        return f"No agent was found with ID '{agent_id}'."

    reports = agent_data["reports"]

    if not reports:
        return (
            f"Agent: {agent_data['name']}\n"
            "Reports: No reports currently recorded."
        )

    return (
        f"Agent: {agent_data['name']}\n"
        "Reports:\n"
        + "\n".join(f"- {report}" for report in reports)
    )


# -------------------------------------------------------------------
# SHORT-LET CURRENT LOOK AND REPORT FUNCTIONS
# -------------------------------------------------------------------

def get_shortlet_current_look(property_id):
    """Return the latest recorded appearance/update of a short-let."""

    shortlet_data = SHORTLETS.get(property_id)

    if shortlet_data is None:
        return (
            f"No short-let record was found for property "
            f"'{property_id}'."
        )

    return (
        f"Short-let Current Look\n"
        f"Property ID: {property_id}\n"
        f"Current Look: {shortlet_data['current_look']}\n"
        f"Update Status: {shortlet_data['current_look_status']}\n"
        f"Last Update: {shortlet_data['last_update']}\n\n"
        "Customers should confirm the latest available information "
        "before booking or paying."
    )


def get_shortlet_reports(property_id):
    """Return reports recorded against a short-let."""

    shortlet_data = SHORTLETS.get(property_id)

    if shortlet_data is None:
        return (
            f"No short-let record was found for property "
            f"'{property_id}'."
        )

    reports = shortlet_data["reported_issues"]

    if not reports:
        return (
            f"Property ID: {property_id}\n"
            "Reports: No reports currently recorded."
        )

    return (
        f"Property ID: {property_id}\n"
        "Reported Issues:\n"
        + "\n".join(f"- {report}" for report in reports)
    )


# -------------------------------------------------------------------
# VAH VERIFICATION NUMBER
# -------------------------------------------------------------------

def get_vah_verification_number(agent_id):
    """
    Return the current VAH Verification Number for an agent.

    The VAH Verification Number is separate from the Agent ID and
    changes every month.
    """

    agent_data = AGENTS.get(agent_id)

    if agent_data is None:
        return f"No agent was found with ID '{agent_id}'."

    return (
        f"VAH Verification Number\n"
        f"Agent ID: {agent_id}\n"
        f"Agent: {agent_data['name']}\n"
        f"Agency: {agent_data['agency']}\n"
        f"Current VAH Verification Number: "
        f"{agent_data['verification_number']}\n"
        f"Number Status: "
        f"{agent_data['verification_number_status']}\n"
        f"Verification Month: "
        f"{agent_data['verification_number_month']}\n"
        f"Update Frequency: "
        f"{agent_data['verification_number_update_frequency']}\n"
        f"Agent Verification Status: "
        f"{agent_data['verification_status']}\n\n"
        "IMPORTANT CUSTOMER SAFETY NOTICE:\n"
        "The VAH Verification Number changes every month. "
        "Always check the current VAH Verification Number and "
        "latest verification status on the Verified Agents and "
        "Homes database/platform immediately before making any "
        "transaction or payment.\n\n"
        "Never rely on an old VAH Verification Number."
    )


# -------------------------------------------------------------------
# VERIFICATION STATUS LIST
# -------------------------------------------------------------------

def get_verification_statuses():
    """Return all available verification statuses."""

    return (
        "Available Verification Statuses:\n"
        + "\n".join(
            f"- {status}"
            for status in VERIFICATION_STATUSES
        )
    )


# -------------------------------------------------------------------
# PAYMENT SAFETY
# -------------------------------------------------------------------

def get_payment_safety_guidance():
    """Return important payment and transaction safety guidance."""

    return (
        "Verified Agents and Homes Payment Safety Guidance\n\n"
        "Before making any payment or transaction with an agent:\n"
        "1. Confirm the agent's identity.\n"
        "2. Confirm the agent's current verification status.\n"
        "3. Confirm the agent's current VAH Verification Number.\n"
        "4. Check the Verified Agents and Homes database/platform "
        "for the latest monthly update.\n"
        "5. Do not rely on an old verification number.\n"
        "6. Check for any reports or warnings associated with the agent.\n"
        "7. Verify the relevant property and documents where applicable.\n"
        "8. If information cannot be confirmed, do not proceed until "
        "the matter has been reviewed.\n\n"
        "IMPORTANT:\n"
        "VAH Verification Numbers change every month. A previous "
        "month's number should not be treated as the current number."
    )